services:
  db:
    image: postgres:16-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: support_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d support_bot"]
      interval: 5s
      timeout: 5s
      retries: 10

  bot:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"    
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head    

volumes:
  pgdata: