"""baseline

Revision ID: 5e02ecaf5b7e
Revises: 
Create Date: 2026-02-18 19:22:38.754115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e02ecaf5b7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sleep_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_choices_role'), 'user_choices', ['role'], unique=False)
    op.create_index(op.f('ix_user_choices_user_id'), 'user_choices', ['user_id'], unique=False)
    op.create_table('user_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('menu_message_id', sa.BigInteger(), nullable=True),
    sa.Column('business_connection_id', sa.String(length=128), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    op.drop_index(op.f('ix_user_choices_user_id'), table_name='user_choices')
    op.drop_index(op.f('ix_user_choices_role'), table_name='user_choices')
    op.drop_table('user_choices')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
